### ISSUE TITLE
Possible bug in 0.2.1

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/hypershield#9]
Any time we run `rake db:schema:load` in our CI suite to test adding v0.2.1, we're getting this:

```
rake db:schema:load
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/app/db/schema.rb:16:in `block in <main>'
/app/db/schema.rb:13:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

These are lines 13-16 in our schema:

```
ActiveRecord::Schema.define(version: 2020_12_11_023305) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "btree_gin"
```

Here's a longer trace:

```

rake aborted!
--
  | ArgumentError: wrong number of arguments (given 2, expected 1)
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:390:in `enable_extension'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:890:in `block in method_missing'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:858:in `block in say_with_time'
  | /bundle/gems/benchmark-0.1.0/lib/benchmark.rb:293:in `measure'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:858:in `say_with_time'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:879:in `method_missing'
  | /bundle/gems/hypershield-0.2.1/lib/hypershield/migration.rb:11:in `method_missing'
  | /bundle/gems/strong_migrations-0.7.3/lib/strong_migrations/migration.rb:11:in `block in method_missing'
  | /bundle/gems/strong_migrations-0.7.3/lib/strong_migrations/checker.rb:297:in `perform'
  | /bundle/gems/strong_migrations-0.7.3/lib/strong_migrations/migration.rb:10:in `method_missing'
  | /app/db/schema.rb:16:in `block in <main>'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:50:in `instance_eval'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:50:in `define'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/schema.rb:46:in `define'
  | /app/db/schema.rb:13:in `<main>'
  | /bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  | /bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:328:in `load_schema'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:425:in `block in load_schema_current'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `each'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:424:in `load_schema_current'
  | /bundle/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:400:in `block (3 levels) in <main>'
  | /bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
  | /bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  | /bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  | /bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
  | /bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  | /bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
  | /bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
  | /bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  | /bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
  | /bundle/bin/bundle:23:in `load'
  | /bundle/bin/bundle:23:in `<main>'
  | Tasks: TOP => db:schema:load
  | (See full trace by running task with --trace)

```

We're running Rails 6.0.3.4, Ruby 2.6.6, PG 12, and this fails with both versions 0.7.3 and 0.7.4 of `strong_migrations` (also featured in the trace).

This isn't a massive blocker for us, but it wasn't immediately apparent why or how `enable_extension` is getting called with a second argument. Is this change to `method_missing` for Ruby 2.7 warnings somehow now passing two instead of three arguments?

https://github.com/ankane/hypershield/commit/a6d7f68eb665154c971eb0f33928eadd5e8def79#diff-a6cd483bcd9cc30796757cba01620d01326a63ee10ba188300758609eee3cd69R3

**Comment by ankane** [comment]
Hey @geoffharcourt, thanks for reporting! Pushing out a new release now.

**Comment by geoffharcourt** [comment]
@ankane thanks very much for the quick fix!
